
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arsenal-prod-stakater-nordmart-review-ui
  namespace: rh-openshift-gitops-instance
  labels:
    stakater.com/tenant: arsenal
    stakater.com/env: prod
    stakater.com/kind: prod  
spec:
  destination:
    namespace: arsenal-prod
    server: 'https://kubernetes.default.svc'
  project: arsenal
  source:
    path: 01-arsenal/02-stakater-nordmart-review-ui/03-prod
    repoURL: 'https://github.com/stakater/nordmart-apps-gitops-config.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

