
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arsenal-prod-stakater-nordmart-review-api
  namespace: rh-openshift-gitops-instance
  labels:
    stakater.com/tenant: arsenal
    stakater.com/env: prod
    stakater.com/kind: prod      
spec:
  destination:
    namespace: arsenal-prod
    server: 'https://kubernetes.default.svc'
  source:
    path: 01-arsenal/01-stakater-nordmart-review-api/03-prod
    repoURL: 'https://github.com/stakater/nordmart-apps-gitops-config.git'
    targetRevision: HEAD
  project: arsenal   
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

