apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus-helm-auth-forked
spec:
  secretStoreRef:
    name: tenant-vault-secret-store
    kind: SecretStore
  refreshInterval: "1m0s"
  target:
    name: nexus-helm-auth-forked
    creationPolicy: 'Owner'
    template:
      type: Opaque
  dataFrom:
    - key: arsenal/nexus-helm-auth-forked
