apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nordmart-ssh-creds
spec:
  secretStoreRef:
    name: tenant-vault-secret-store
    kind: SecretStore
  refreshInterval: "1m0s"
  target:
    name: nordmart-ssh-creds
    creationPolicy: 'Owner'
    template:
      data:
        id_rsa: "{{ .id_rsa | toString }}"
  data:
    - secretKey: id_rsa
      remoteRef:
        key: ssh-config
        property: id_rsa

apiVersion: v1
kind: Secret
metadata:
  name: nordmart-ssh-creds # Name of Secret
data:
  id_rsa: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNES2lSaXI0UGxjYWh0RmtvenUzcVMyZHNndUltVnk4bkE3aHVFTmp3eUdGd0FBQUpoY2oxeUhYSTljCmh3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDREtpUmlyNFBsY2FodEZrb3p1M3FTMmRzZ3VJbVZ5OG5BN2h1RU5qd3lHRncKQUFBRUF2Z1hPTHFoV1RrMTZlUGxpbHVsc2JpazdLSnVIQnBCZEhKdzJPY0xhSVpzcUpHS3ZnK1Z4cUcwV1NqTzdlcExaMgp5QzRpWlhMeWNEdUc0UTJQRElZWEFBQUFEM04wWVd0aGRHVnlMV2RzYjJKaGJBRUNBd1FGQmc9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
