apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chelsea-build-tekton-pipelines
  namespace: rh-openshift-gitops-instance
  labels:
    stakater.com/tenant: chelsea
    stakater.com/env: build
    stakater.com/kind: build    
spec:
  destination:
    namespace: chelsea-build
    server: 'https://kubernetes.default.svc'
  project: chelsea
  source:
    path: 02-chelsea/00-tekton-pipelines/00-build
    repoURL: 'https://github.com/stakater/nordmart-apps-gitops-config.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
