apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chelsea-dev-stakater-nordmart-inventory
  namespace: rh-openshift-gitops-instance
  labels:
    stakater.com/tenant: chelsea
    stakater.com/env: dev
    stakater.com/kind: dev     
spec:
  destination:
    namespace: chelsea-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: 02-chelsea/01-stakater-nordmart-inventory/01-dev
    repoURL: 'https://github.com/stakater/nordmart-apps-gitops-config.git'
    targetRevision: main
  project: chelsea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true