apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chelsea-stage
  namespace: rh-openshift-gitops-instance
spec:
  destination:
    namespace: rh-openshift-gitops-instance
    server: 'https://kubernetes.default.svc'
  source:
    path: 02-chelsea/00-argocd-apps/02-stage/
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: main
    directory:
      recurse: true
  project: chelsea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

