apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chelsea-stage-stakater-nordmart-inventory
  namespace: rh-openshift-gitops-instance
  labels:
    stakater.com/tenant: chelsea
    stakater.com/env: stage
    stakater.com/kind: stage     
spec:
  destination:
    namespace: chelsea-stage
    server: 'https://kubernetes.default.svc'
  source:
    path: 02-chelsea/01-stakater-nordmart-inventory/02-stage
    repoURL: 'https://github.com/stakater/nordmart-apps-gitops-config.git'
    targetRevision: main
  project: chelsea
  syncPolicy:
    automated:
      prune: true